### ISSUE TITLE
TypeError: (0 , express_rate_limit_1.default) is not a function

### ISSUE THREAD

**Issue by MrXujiang** [nfriedly/express-rate-limit#280] opened 2022-01-04 10:29 UTC
### Description

my version is 6.0.2, but when i use in nest, it occur an error:

(node:5062) UnhandledPromiseRejectionWarning: TypeError: (0 , express_rate_limit_1.default) is not a function

### Library version

6.0.2

### Node version

14.17.6

### Module system

ESM

**Comment by gamemaker1** [comment] 2022-01-04 11:34
Hi @MrXujiang,

This issue looks similar to #275. Could you please answer the following questions so we can help solve your issue:

- How are you importing the library - `const rateLimit = require('express-rate-limit')` or `import rateLimit from 'express-rate-limit'`?
- Do you have `type: module` in your package.json?
- Are you using Typescript? If yes, could you paste your tsconfig.json?

Thanks!

**Comment by gamemaker1** [comment] 2022-01-04 11:37
Also, could you please take a look at [this](https://github.com/nfriedly/express-rate-limit#importing) section of the readme in case something mentioned there solves your problem?

**Comment by DavideViolante** [comment] 2022-01-07 11:36
I encountered this problem too:
```
/home/dave/Job/myproject/dist/server/app.js:19
[1] app.use('/api/', express_rate_limit_1.default({ max: 900, windowMs: 15 * 60 * 1000 }));
[1]                                              ^
[1] 
[1] TypeError: express_rate_limit_1.default is not a function
[1]     at Object.<anonymous> (/home/dave/Job/myproject/dist/server/app.js:19:46)
```

It's happening with "module": "commonjs".

I sent a PR to fix.

**Comment by gamemaker1** [comment] 2022-01-07 11:41
Could you please paste your tsconfig.json?

**Comment by DavideViolante** [comment] 2022-01-07 14:34
```js
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "../dist/server",
    "baseUrl": "",
    "forceConsistentCasingInFileNames": true,
    "noImplicitOverride": true,
    "noPropertyAccessFromIndexSignature": false,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2017",
    "module": "commonjs",
    "types": ["node", "jest"]
    "lib": [
      "es2020",
      "dom"
    ]
  }
}
```

**Comment by DavideViolante** [comment] 2022-01-07 14:47
```ts
import * as dotenv from 'dotenv';
dotenv.config();
import * as express from 'express';
import * as morgan from 'morgan';
import { join } from 'path';
import * as cors from 'cors';
import expressRateLimit from 'express-rate-limit';
```

If I import as express:
```
This expression is not callable.
  Type 'typeof import("/home/dave/Job/myproject/node_modules/express-rate-limit/dist/index")' has no call signatures.ts(2349)
```

**Comment by DavideViolante** [comment] 2022-01-07 14:50
I think the correct behaviour should be:
- if I've esModuleInterop false, I've to import like express
- if I've esModuleInterop true, I've to import as above
- Another different option would be like path, import { rateLimit } from 'express-rate-limit

**Comment by gamemaker1** [comment] 2022-01-07 15:01
The `import rateLimit from 'express-rate-limit'` syntax is usually used only when importing ES modules in ES6+ code. However, since you are compiling the code to commonjs (`module: commonjs` in tsconfig.json), Typescript imports the CJS version of the library. The CJS version is exported using `module.exports`, and not `export default`, which causes this problem.

A clean solution is to enable the `esModuleInterop` flag, which allows you to use the `import ... from '...'` syntax with CommonJS modules too. However, if you still do not wish to switch on the `esModuleInterop` flag, you can do one of the following:

1. Suppress the error with a `@ts-expect-error` comment.
2. Change `target: es2017` to `target: commonjs` in tsconfig.json, since you are anyways targeting a commonjs environment. This will fix the import issue.

**Comment by DavideViolante** [comment] 2022-01-07 15:26
target commonjs is not a valid option for tsconfig. I'm sure there is something wrong in this repo not in my project, that imports hundreds of different packages without any problem.

Btw, I was trying to re-generate the typings for this project and it seems to work. You should to get rid of `dts-bundle-generator` and use official TypeScript compiler `tsc` to generate the typings, for example the following seem to work correctly:
`"build:types": "tsc --declaration --emitDeclarationOnly --outDir dist source/index.ts",`

Can you give it a try, in particular for non cjs project? Thanks

**Comment by gamemaker1** [comment] 2022-01-08 05:39
> `target: commonjs` is not a valid option for tsconfig.

Ohk - sorry about the wrong answer.

> I was trying to re-generate the typings for this project and it seems to work

This is a runtime error - types should not matter here. Also, `tsc` does not generate one single type declaration file - `dts-bundle-generator` uses `tsc` to do that.

> Can you give it a try, in particular for a *non-cjs* project?

AFAIK, this bug seems to be happening only in Typescript CommonJS projects without the `esModuleInterop` flag.

---

I did some more documentation reading, and found the following:

- Libraries like Express recommend either turning on the `esModuleInterop` flag, so you can use `import express from 'express'` instead of `import * as express from 'express'`.
- If you cannot turn on the `esModuleInterop` flag, the other [recommended way](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/express/index.d.ts#L11-L12) is to use `import express = require('express')`. I remember having suggested this earlier.
- Otherwise, you could simply import it like you are doing currently with Express - `import * as rateLimit from 'express-rate-limit'` - and suppress the type error using `@ts-expect-error`.

**Comment by DavideViolante** [comment] 2022-01-08 11:01
Thank you, but I think one should be able to import rateLimit like express for cjs projects without the need to suppress the error (your third case).
Also, in rateLimit v5 this kind of import was already possible without errors.
I will try to send a proper PR if I find out how to fix it. Thanks anyway.

**Comment by gamemaker1** [comment] 2022-01-08 11:06
> I think one should be able to import rateLimit like express for cjs projects without the need to suppress the error (your third case).

That style of import (`import * as express from 'express'`) is not compliant with the ES6 modules specification, and should not ideally be used - this is the reason why the `esModuleInterop` flag was introduced. [Here](https://stackoverflow.com/a/56348146) is a detailed explanation regarding this. 

I have already mentioned the recommended solution - use `import express = require('express')`. Could you please try using this for the `express-rate-limit` library too and let me know if it works? (`import rateLimit = require('express-rate-limit')`)

Thanks

**Comment by DavideViolante** [comment] 2022-01-08 11:32
> [I have already mentioned](https://github.com/nfriedly/express-rate-limit/issues/280#issuecomment-1007890936) the recommended solution - use `import rateLimit = require('express-rate-limit')`. Could you please try using this and let me know if it works?
> 
> Thanks

Actually it doesn't work (I thought it was).

```ts
import expressRateLimit = require('express-rate-limit');
...
app.use('/api/', expressRateLimit({ max: 900, windowMs: 15 * 60 * 1000 }));
^
This expression is not callable.
  Type 'typeof import("/home/dave/Job/myproject/node_modules/express-rate-limit/dist/index")' has no call signatures.ts(2349)
```

it seems to work like this
```ts
const expressRateLimit = require('express-rate-limit');
```

but then you don't have intellisense for typings anymore... (expressRateLimit becomes `any`)

There is no other library that _needs_ to be imported with require in all the projects I worked. This is what makes me think that something should be fixed here, but not sure what exactly is yet. (We will find out btw).

**Comment by gamemaker1** [comment] 2022-01-08 11:41
> Actually it doesn't work (I thought it was).

Oh - could you please paste the output of the following?

```ts
import rateLimit = require('express-rate-limit')

console.log(rateLimit)
```

> We will find out btw

Yes we will :D 

Thanks for your patience!

**Comment by gamemaker1** [comment] 2022-01-08 11:46
Also, do you have `type: module` in package.json?

**Comment by gamemaker1** [comment] 2022-01-10 10:37
> Log output: `[Function: rateLimit]`

Ok so that should work at runtime but gives a type error.

> I made a reproduction repo.

Thanks, that will help us debug it better :D

I think what we need is separate declaration files for the CJS and ESM files. Not sure if that is even possible though...

**Comment by gamemaker1** [comment] 2022-01-10 10:53
So a bit more searching and here is what we could do:

> Two messy solutions

1. We could ask developers using CommonJS to switch on the `esModuleInterop` flag, without which they would have to use the `import rateLimit = require('express-rate-limit')` and suppress any type errors (if they are using Typescript).
2. We could switch to using the `export =` syntax in our type declaration file (we currently use `export default`), and then ask ESM developers (people with `type: module` in their package.jsons) to switch on the `esModuleInterop` flag, without which they would have to resort to the `import * as rateLimit from 'express-rate-limit'` hack and suppress any type errors (if they are using Typescript).

> Clean but major-version-change solution

3. We could switch to using a named export (`import { rateLimit } from 'express-rate-limit'`), which keeps both CommonJS and ESM developers happy (in theory - I will test this and get back to you), but requires a major version bump.

IMO the third solution (still need to test it but if it works) will keep everyone happy and remove the [hacky footer we currently tack on](https://github.com/nfriedly/express-rate-limit/blob/master/package.json#L53) to the end of the CJS file.

@nfriedly thoughts?

**Comment by DavideViolante** [comment] 2022-01-10 13:31
Maybe third solution can be made without breaking change, exporting _both_ default and named function.
Ref: https://bignerdranch.com/blog/default-exports-or-named-exports-why-not-both/

**Comment by gamemaker1** [comment] 2022-01-10 14:38
That's a good idea - we could keep both, and next time we make a breaking change, we could remove the default export.

**Comment by nfriedly** [comment] 2022-01-10 15:31
Oh, wait, that's what you all were just discussing, wasn't it? Sorry, I'm still a bit groggy this morning...

**Comment by gamemaker1** [comment] 2022-01-10 16:39
> module.exports = rateLimit; module.exports.default = ratelimit;

Ooohh this is a good idea, this could make it work without any flags or whatever

**Comment by nfriedly** [comment] 2022-01-10 16:48
I suppose you could do one more to make it work as raw, default, and named exports for the commonjs version:

```js
module.exports = rateLimit; module.exports.default = ratelimit; module.exports.rateLimit = rateLimit;
```

That should work for just about anyone.

**Comment by nfriedly** [comment] 2022-01-10 16:53
Oh, and then the ESM version should do

```diff
  export default rateLimit
+ export rateLimit
```

**Comment by gamemaker1** [comment] 2022-01-11 02:48
https://github.com/nfriedly/express-rate-limit/issues/280#issuecomment-1008995880 works, yay! Tested it out with the reproduction repo that @DavideViolante made.

I will add the named export too and then open a PR.

**Comment by gamemaker1** [comment] 2022-01-11 04:12
Created #285

**Closed** 2022-01-12 03:41 UTC
Labels: bug
